### ISSUE TITLE
Always display request url

### ISSUE THREAD

**Issue by sporto** [warrenday/graphql-network-inspector#1]
Hi
Thanks for doing this, looks really useful.

We add debugging information in the request query string. E.g. `/graphql?id=abc` this helps us a lot to find where a graphql request originates from.

It would be really useful if this extension would display the request url in the left panel.

Thanks

**Comment by warrenday** [comment]
Hi @sporto 

Thanks for using the tool, I'm glad to be able to help out other developers :)

The request URL is already displayed in the left column. Although only when the right panel is not expanded.

<img width="673" alt="Screenshot 2020-10-04 at 18 10 57" src="https://user-images.githubusercontent.com/2871038/95022102-fe713a00-066c-11eb-8c7b-be07ccc80275.png">

Was the concern more related to showing this data while the right panel is also open?

**Comment by sporto** [comment]
@warrenday sorry, I somehow didn't notice that it was already there when not expanded. But yes, it would be a lot more useful to be able to see the request url all the time.

**Comment by warrenday** [comment]
@sporto no problem. I'll add this feature to the pipeline and hope to release something within the next months. I'll close this issue for now as the URL is still accessible in the table view.
