### ISSUE TITLE
Possibility to work over SSR pages?

### ISSUE THREAD

**Issue by surajsharma** [warrenday/graphql-network-inspector#103]
Just wondering if this thing can work on pages rendered server side

**Comment by warrenday** [comment]
Since those requests are occurring within the server, we don't have access client side.

The only way I see this working is if we release an accompanying library/middleware (such as an npm library) which could send data back to this app.

Any other thoughts on how to achieve this?

**Comment by surajsharma** [comment]
> Any other thoughts on how to achieve this?

could there be a way to add something to the headers that could mark a request off as gql and so on..?

**Comment by warrenday** [comment]
Closing as no current plans for SSR support, as this is outside of the current scope of the inspector.
