### ISSUE TITLE
Cannot listen all POST request

### ISSUE THREAD

**Issue by LeiChen1999** [warrenday/graphql-network-inspector#106]
**Describe the bug**
I cannot get all POST request by using *graphql network*. I saw some other POST request using *Network*  by Chrome inspector, but not showing on *graphql network*.

**Desktop (please complete the following information): Macbook Pro M2

- OS: MacOS
- Chrome Version: 114.0.5735.106

**Comment by warrenday** [comment]
Hey @LeiChen1999 sorry for the slow reply. I've been away. Could you share the body of some of the requests which did not show in the graphql network inspecor?

**Comment by warrenday** [comment]
Close due to inactivity.
