### ISSUE TITLE
Cannot read properties of null (reading 'done') 

### ISSUE THREAD

**Issue by ComicDread** [warrenday/graphql-network-inspector#107]
so as the title said i cannot read properties of null (reading 'done')
the only problem is i actually don't want to read it 🤨
i never asked to read the property of done..

i am using GraphQL network and done doesn't even look null!!

{1 item
"data":{1 item
"tasks":[1 item
0:{4 items
"name":"aadsa"
"done":false
"id":"5iuF8ogBxAX3KEei4ac8"
"__typename":"Task"
}
]
}

and this is the query i am trying to send 

mutation newupdatedTitleTask($id: ID!, $input: titleInput!) {
  updatedTitle(id: $id, input: $input)
}
{
  "id": "5iuF8ogBxAX3KEei4ac8",
  "input": {
    "name": "aadsaa"
  }
}

**Comment by warrenday** [comment]
Sorry for the slow reply @ComicDread I've been on holiday. Could you share the full body of the request from the standard network inspector?

Also is this being sent with POST?

**Comment by ComicDread** [comment]
hi i solved already 👍  :)

**Comment by warrenday** [comment]
What was the issue?

**Comment by ComicDread** [comment]
sorry i really do not remember, in 2 weeks i added so many features and discovered so many bugs that my mind is full 
🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻
