### ISSUE TITLE
Doesn't clear on refresh

### ISSUE THREAD

**Issue by adi518** [warrenday/graphql-network-inspector#11]
Great work on this very much needed extension. I ran into an issue where it doesn't clear the log on refresh. I'm sure it's an easy fix.

**Comment by warrenday** [comment]
This is intentional (you can clear with the bin icon manually). However, a check box to choose if to clear on refresh would be nice. I'll look into adding something.

**Comment by adi518** [comment]
In that case, I definitely think it should follow the default devTools behavior, which clears the log on refresh _unless_ you check "Preserve log" under settings.
