### ISSUE TITLE
Support Queries / Mutations using the WS transport

### ISSUE THREAD

**Issue by whygee-dev** [warrenday/graphql-network-inspector#112]
**Is your feature request related to a problem? Please describe.**
Only queries and mutations using the HTTP transport are detected and shown via the extension.

**Describe the solution you'd like**
The extension ideally should also monitor ws connections and detect the queries / mutations made.

**Comment by whygee-dev** [comment]
are you open to a PR implementing this ?

**Comment by warrenday** [comment]
Absolutely, it's a highly requested feature, I haven't had time to get around to it, but would welcome a pr. ⭐️

**Comment by warrenday** [comment]
This is in progress. Will be the next major release.

**Comment by warrenday** [comment]
Closing as Beta feature for subscriptions now added in 2.18.0
