### ISSUE TITLE
Search full request - jump to the point in the request where the match is found

### ISSUE THREAD

**Issue by iainmck29** [warrenday/graphql-network-inspector#113]
I use this network inspector everyday and it's a great tool but one annoying thing I find is with the Search full request bar. If I have a very large reponse in which I may want to search for some data within it then I'll use this tool but while it finds the match no problem, i then have to trawl through a huge response to actually find the highlighted bit where the search match exists.

It would be great if clicking on the search result caused the scroll on the response tab to auto jump to the point where the match exists.

**Comment by iainmck29** [comment]
That would be great. I was thinking of being able to click any of the given matches in the list and it would jump straight to that position rather than going through each in case I may have a lot of matches but either works anyway!

**Comment by jadnhm** [comment]
I would def love this. If I've got a page making a gql request that returns a particular payload I want to give it something to search for (JSON path?) and just show me that part of the response.

**Comment by warrenday** [comment]
This is currently planned. I'll get to it once subscriptions is finished and released.

**Comment by jadnhm** [comment]
@warrenday I presume this didn't get picked up/completed... any updates?

**Comment by warrenday** [comment]
This has been released for a while. Currently shows matches in yellow. Jumps to the first match.

<img width="432" alt="Screenshot 2024-04-22 at 18 57 19" src="https://github.com/warrenday/graphql-network-inspector/assets/2871038/4f898869-43ae-43dc-a4e9-5753fe71806f">

**Comment by jadnhm** [comment]
oh amazing! how did I miss it? 🤦 haha  

I will look and try it out ASAP

**Comment by warrenday** [comment]
Closing this as we do have jump to search. If you're after something more, please feel free to raise a PR. All are welcome!
