### ISSUE TITLE
It always shows `No requests have been detected` 

### ISSUE THREAD

**Issue by zhaoyi0113** [warrenday/graphql-network-inspector#119]
**Describe the bug**

When open this tab in chroms dev tool, it shows `No requests have been detected` even there are many graphql request.

**Screenshots**

![image](https://github.com/warrenday/graphql-network-inspector/assets/3355579/7ec2c0d9-eff8-40fb-8445-cd274b66e9b3)

**Desktop (please complete the following information):**

- OS: Mac OS 14.0
- Chrome Version: 120.0.6099.109

**Comment by warrenday** [comment]
Hey @zhaoyi0113 please post the exact payload of your graphql request from the standard network tab. We usually see no detection for non-standard formats.

**Comment by warrenday** [comment]
Closing as likely issue with formatting. Please re-open if needed.

**Comment by lopezjurip** [comment]
I'm having a similar issue. Looks like it's hardcoded to search only for `/graphql` requests. Mine is at `/v1/graphql` and I can't find a way to change this setting.

**Comment by arturkin** [comment]
Have the same issue, works on medium.com but  doesn't work with my custom API endpoint name since recently. It was picking up my queries just fine before.

**Comment by arturkin** [comment]
Figured it out — in order for extension to work, we need to disable service worker bypass in dev tools. Apparently, interception isn't playing nice with  service workers. 

Thanks for the help! What a great extension.
