### ISSUE TITLE
Bug report: Invalid regular expression: /Theory of knowledge (/i: Unterminated group

### ISSUE THREAD

**Issue by jatin-toddleapp** [warrenday/graphql-network-inspector#122]
I encountered an error: Invalid regular expression: /Theory of knowledge (/i: Unterminated group

**Comment by warrenday** [comment]
Hey @jatin-toddleapp could you provide a screenshot or video, unable to see error with same text. Was this filter or search?

**Comment by jatin-toddleapp** [comment]
after copy & pasting the text with brackets, if I remove the closing bracket.

Uploading Screen Recording 2024-02-19 at 5.25.32 PM.mov…
