### ISSUE TITLE
Plugin didn't show up in v2.19.2

### ISSUE THREAD

**Issue by HappySean2845** [warrenday/graphql-network-inspector#123]
**Describe the bug**
Plugin didn't show up in the latest v2.19.2

**To Reproduce**
Just update to v2.19.2

**Expected behavior**
Show the plugin

**Screenshots**
![image](https://github.com/warrenday/graphql-network-inspector/assets/7857661/021044f6-d2be-4622-af8f-0c1c3b172a54)

**Desktop (please complete the following information):**

- OS: macOS 14.0 (23A344)
- Chrome Version 122.0.6261.57

**Additional context**

**Comment by warrenday** [comment]
This issue seems intermittent for multiple users. Did closing and re-opening dev tools resolve the issue for you?

**Comment by HappySean2845** [comment]
> This issue seems intermittent for multiple users. Did closing and re-opening dev tools resolve the issue for you?

Yes I have tried several times and uninstall/install the plugin for several times, it didn't help

**Comment by escontreras** [comment]
I have a same problem. Plugin didn't show up in devtools

- Chrome Version 122.0.6261.95
- Extension Version 2.19.2

**Comment by warrenday** [comment]
Is this from a fresh install or after auto upgrade? Also is it permanently gone, or does it re-appear after closing/opening devtools?

**Comment by warrenday** [comment]
I'll do some testing tonight on a fresh install and try to recreate. Annoyingly I've never seen this issue myself, but plenty have reported it.

**Comment by escontreras** [comment]
It is in some users I don't know what the reason may be, on my laptop I can see the tab without problems

**Comment by warrenday** [comment]
I've been looking through all of the chrome api's we use within the app. Nothing requires special permissions, so struggling to figure out what causes this.

Is anyone able to see any errors logged from the extension under the "manage extensions" window?
```
chrome://extensions/
```

<img width="435" alt="Screenshot 2024-02-29 at 19 07 40" src="https://github.com/warrenday/graphql-network-inspector/assets/2871038/10235450-d829-406b-b990-504acaa445ef">

**Comment by escontreras** [comment]
i don't not see errors

![image](https://github.com/warrenday/graphql-network-inspector/assets/5234722/91438c96-705d-4ea1-a110-2aeb3e51bd6f)

**Comment by escontreras** [comment]
I'm resolve the problem, press 12 to open dev tools and f1 to open the config page and press the button reset default configurations

**Comment by ramiel** [comment]
Yes, this solves the problem. I tried to check for any logs before resetting but with no luck. The problem for me happened on a browser with the extension previously working and on a browser with the extension just installed. If I find something I'll report here

**Comment by warrenday** [comment]
Appreciate it!

**Comment by warrenday** [comment]
I'll add this guide to the main readme, should help others.
