### ISSUE TITLE
Add automatic JWT parsing

### ISSUE THREAD

**Issue by dutzi** [warrenday/graphql-network-inspector#125]
I have a branch where JWT are automatically parsed and viewed as JSON (instead of the base-64 string).

Here's how it looks like (note I'm going a step further and displaying the expiration date as readable date + "time until" pretty print).

Before:

![image](https://github.com/warrenday/graphql-network-inspector/assets/927310/51404221-2b3b-4a41-8201-637977277e62)

After:

![image](https://github.com/warrenday/graphql-network-inspector/assets/927310/e3a9673c-653b-4897-90d7-b7b265d49f8c)

Would you like me to finalize it as a PR?

**Comment by warrenday** [comment]
Hey @dutzi thanks again for another PR. Could this on click of a checkbox/button?

It's a great idea, however not all users will want this by default.

Just to note: You can click the header directly to copy it, so we can't have the click to parse there.

**Comment by warrenday** [comment]
I've gone ahead and progressed with this one and added the parsing via double click. I'll close this issue for now, the feature will be in version `2.19.4`.

Readme also updated with mouse and keyboard shortcuts.
