### ISSUE TITLE
Provide a privacy policy in a separate file

### ISSUE THREAD

**Issue by tsufiev** [warrenday/graphql-network-inspector#130]
**Is your feature request related to a problem? Please describe.**
I'd love to use your extension for debugging graphql requests, however my employer has very strict policies regarding which Chrome extensions could be used, since we're dealing with sensitive data.

**Describe the solution you'd like**
Having a separate file with the extension privacy policy, the same was as https://github.com/gorhill/uBlock/wiki/Privacy-policy would help to alleviate our legal team's concerns.

**Describe alternatives you've considered**
I've looked for other extensions from companies which would have a dedicated privacy policy, but their extensions are inferior to yours.

**Additional context**
[Another way](https://chromewebstore.google.com/detail/adobe-acrobat-pdf-edit-co/efaidnbmnnnibpcajpcglclefindmkaj?hl=en-GB) the privacy policy can be provided

**Comment by warrenday** [comment]
Thanks for raising this. Happy to add a policy.

I'll take a look at the one you linked.

**Comment by warrenday** [comment]
Privacy has now been added @tsufiev 
https://github.com/warrenday/graphql-network-inspector/blob/master/PRIVACY.md

**Comment by tsufiev** [comment]
@warrenday Thanks a lot, our legal team is relieved now and we can use it :).
