### ISSUE TITLE
Bug report: Syntax Error: Unexpected character: "/".

### ISSUE THREAD

**Issue by iancalalang** [warrenday/graphql-network-inspector#135]
I encountered an error: Syntax Error: Unexpected character: "/".

**Comment by warrenday** [comment]
Hey, thanks for raising. Could you describe when this happened?

**Comment by gh0stsh0t** [comment]
Hi @warrenday I replicated this bug at https://wine.qantas.com/c/red-wine
It seems like a field in this form `"fieldName": "/"` throws this error

**Comment by warrenday** [comment]
Thank you, that helps a ton!

**Comment by warrenday** [comment]
This has now been fixed in version v2.20.2. The update should be released today or tomorrow.
