### ISSUE TITLE
Does not detect compressed requests

### ISSUE THREAD

**Issue by denis-sokolov** [warrenday/graphql-network-inspector#142]
**Describe the bug**
The extension does not recognize GraphQL requests if they have been sent with an HTTP encoding (namely, “deflate” or “gzip” compression).

**To Reproduce**
1. Open [the interactive demo](https://codesandbox.io/p/sandbox/encoded-graphql-request-7twxvc?file=%2Fsrc%2Findex.ts%3A19%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz7b48030006356jcijy95xz%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz7b48030002356jlo37mprq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz7b48030003356jljb8wqnw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz7b48030005356j84d1qvf0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz7b48030002356jlo37mprq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz7b48030001356jad12zrq2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clz7b48030002356jlo37mprq%2522%252C%2522activeTabId%2522%253A%2522clz7b48030001356jad12zrq2%2522%257D%252C%2522clz7b48030005356j84d1qvf0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz7b48030004356jupxp0z1r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz7b48030005356j84d1qvf0%2522%252C%2522activeTabId%2522%253A%2522clz7b48030004356jupxp0z1r%2522%257D%252C%2522clz7b48030003356jljb8wqnw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz7b48030003356jljb8wqnw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D).
2. Open the developer tools.
3. Press on both buttons.
4. Notice how extension shows only one GraphQL request.

**Expected behavior**
Expected to see two GraphQL requests.

Notice that both requests worked the same way and showed up in the console and the browser’s network tab.

**Additional context**
Relevant code in the repo:
https://github.com/warrenday/graphql-network-inspector/blob/22e1393ab598e40575734a6850b426217812e9c7/src/helpers/networkHelpers.ts#L267-L270

It seems we need to recognize popular Content-Encoding header values (deflate and gzip) and decode the HTTP body before detecting GraphQL queries in it.

**Comment by warrenday** [comment]
Thanks for adding the interactive demo, it's been super helpful in getting this feature working. I'll be releasing an update in a couple days.

**Comment by warrenday** [comment]
2.21.4 has no been released with the patch to handle compressed queries.

The demo is now working:

<img width="721" alt="Screenshot 2024-09-06 at 09 04 02" src="https://github.com/user-attachments/assets/6cf0293c-4e74-4a8e-b9ce-9c19919fc216">

Thanks for raising and putting the demo together. Completely new to the native streaming/compression API's so this was a fun one to work on.
