### ISSUE TITLE
Filter box / Invert checkbox behaviour 

### ISSUE THREAD

**Issue by QueenFliss** [warrenday/graphql-network-inspector#143]
**Describe the bug**
if you close and open dev tools the extension remembers the checkbox (eg invert) but forgets what you have entered in the filter box.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to website you want to inspect api calls on 
2. Click on filter and type anything
3. Hit 'Invert' 
4. Close dev tools and reopen it  

**Expected behavior**
either the invert checkbox is unchecked or filter text is remembered 

**Screenshots**
**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.5
- Chrome Version 127.0.6533.89

**Comment by warrenday** [comment]
Hey @QueenFliss this is now in version 2.21.2

https://github.com/warrenday/graphql-network-inspector/commit/271e378d4995aa39d78e2fac5bbd11318ba96b34

Will be released to chrome in the next couple days.
