### ISSUE TITLE
Bug report: Cannot read properties of undefined (reading 'impl')

### ISSUE THREAD

**Issue by eliasyishak** [warrenday/graphql-network-inspector#147]
I encountered an error: Cannot read properties of undefined (reading 'impl')

Not sure what is wrong but whenever I try to open up the inspector to view gql calls, nothing shows up and prompts me with the report bug button

![image](https://github.com/user-attachments/assets/97b92644-6e09-46e3-934e-aedd2c9d96af)

**Comment by cqueiroz-ciandt** [comment]
Same here.

**Comment by warrenday** [comment]
I've rolled back the latest release until I can test this issue further. In the meantime, could you right-click (inspect) on the devtools extension window and see if there is any more info in the console?

**Comment by eliasyishak** [comment]
Hm not erroring anymore, it's working as expected..maybe a flake somewhere?

**Comment by warrenday** [comment]
Closed for now. Please re-open if issue occurs again.
