### ISSUE TITLE
Publish new Firefox release

### ISSUE THREAD

**Issue by Nezteb** [warrenday/graphql-network-inspector#155]
**Is your feature request related to a problem? Please describe.**

Chrome has version `2.22.0`: https://chromewebstore.google.com/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln

Firefox only has version `2.19.0` from almost a year ago: https://addons.mozilla.org/en-US/firefox/addon/graphql-network-inspector/

**Describe the solution you'd like**

Publish `2.22.0` to Firefox.

**Describe alternatives you've considered**

I could build from source but wanted to make the suggestion. 😄 

**Additional context**

I love this extension.

**Comment by warrenday** [comment]
Hey @Nezteb. I've uploaded the latest version!

**Comment by warrenday** [comment]
I have rolled back to an older version. Turns out firefox does not full support manifest version 3, so had issues upgrading. I'll need to wait for manifest v3 to be fully supported to enable the use of webRequest API.
