### ISSUE TITLE
Bug report: t.webRequest is undefined

### ISSUE THREAD

**Issue by JakkNaj** [warrenday/graphql-network-inspector#156]
I encountered an error in Firefox: t.webRequest is undefined
yn/</<@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:2013544
yn/<@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:2013704
Bl@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:756804
6813/t.unstable_runWithPriority@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:872156
qa@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:697123
Ml@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:756265
4463/Fl/<@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:756176
L@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:871216
6813/S.port1.onmessage@moz-extension://7cceb058-5b71-4277-811f-e73dfbb7df38/static/js/main.9c7d30cf.js:2:869938

**Comment by BernardoYeb** [comment]
I'm getting the same error here in firefox

**Comment by warrenday** [comment]
Thanks guys, I'll take a look.

**Comment by warrenday** [comment]
I have rolled back to an older version. Turns out firefox does not full support manifest version 3, so had issues upgrading.
