### ISSUE TITLE
Bug report: The panel show "No requests have been detected" when the  api ends with .json.

### ISSUE THREAD

**Issue by neil1222** [warrenday/graphql-network-inspector#161]
**Describe the bug**
the panel show "No requests have been detected" when the api ends with .json.
For example, Shopify's API ends with .json, you can view its documentation: https://shopify.dev/docs/api/storefront
![image](https://github.com/user-attachments/assets/7998d10d-188b-45f4-8c4f-d77565267bed)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Chrome Version [e.g. 22]

**Additional context**
Maybe it's because of this code:
graphql-network-inspector/src/helpers/networkHelpers.ts:52
```javascript
export const urlHasFileExtension = (url: string): boolean => {
  // Check if URL ends with a file extension (e.g. .js, .css, .png)
  const urlParts = url.split('/')
  const lastPart = urlParts[urlParts.length - 1]
  return lastPart.includes('.')
}
...

if (urlHasFileExtension(details.request.url)) {
        return
      }
```

**Comment by warrenday** [comment]
Thanks for raising. This is fixed in https://github.com/warrenday/graphql-network-inspector/pull/163

Will be in next release.
