### ISSUE TITLE
Proposal to move the clear request button in the toolbar

### ISSUE THREAD

**Issue by tomma5o** [warrenday/graphql-network-inspector#24]
Hey, Warren nice to meet you! ✋ 

First of all thanks for this extension! It was very helpful to me!

The only inconvenient thing I noticed in the day-to-day use, is the "clear button" that jumps at the end of the screen when you close the details of a request and return on the left when you open again the details.

If you like the fix I've made already a PR 👍 

![image](https://user-images.githubusercontent.com/8134038/132757899-2b0f1fb9-b168-4bf6-996d-89b2ec21c858.png)

**Comment by warrenday** [comment]
Hi @tomma5o thanks for raising this issue and the PR. I agree with the problem so I'll review this now.

**Comment by warrenday** [comment]
Closing this as PR is in progress.
