### ISSUE TITLE
Inspector tab goes totally blank when clicking on a request

### ISSUE THREAD

**Issue by rocketraman** [warrenday/graphql-network-inspector#29]
Clicked on a request and the inspector tab goes totally blank. No errors in the console.
![Screenshot_20210921_224843](https://user-images.githubusercontent.com/53049/134275687-4d90c636-497d-4903-99b6-c6983d7c9aaf.png)

**Comment by warrenday** [comment]
Thanks for raising this issue. Did you have the search panel open at the time of the error?

**Comment by rocketraman** [comment]
I didn't even know there was a search tab lol. I just installed the extension and only bothered to take the time to create this because it has great reviews. :)

**Comment by warrenday** [comment]
Appreciate you raising the issue. I'll try to recreate the bug and push a fix.

**Comment by warrenday** [comment]
Fix is ready for this. I'll release an update today
https://github.com/warrenday/graphql-network-inspector/pull/30

**Comment by rocketraman** [comment]
Nice work, thank you. Looking forward to trying out the extension.

**Comment by warrenday** [comment]
Hey @rocketraman hopefully your issue is now resolved with release 2.3.5

**Comment by rocketraman** [comment]
> Hey @rocketraman hopefully your issue is now resolved with release 2.3.5

It is, thank you!
