### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by michael-infinitusai** [warrenday/graphql-network-inspector#33]
Are there any plans to support inspecting GQL subscriptions in addition to queries and mutations?

**Comment by warrenday** [comment]
At the moment I am adding mocking support but will take a look into subscriptions afterwards. It is on the roadmap but I felt it wasn't high priority.

**Comment by anthonydelage** [comment]
+1 for mocking, I can't find anything put there to do this and it'd be a huge help for what I'm currently working on.

**Comment by robertherber** [comment]
Great extension! So much easier and quicker than the network tab to get an overview for GraphQL data. But really missing the subscriptions, so a big +1 on this feature request :)

**Comment by warrenday** [comment]
It would be great to get an idea of how everyone is working with subscriptions at the moment. 

Which libraries are you using?
Do you communicate over websockets or another protocol?

The end goal of this feature is to  be platform/protocol agnostic. But it would be great to get an idea of where to start. As not everyone is using Apollo. :)

**Comment by robertherber** [comment]
I'm currently using Apollo, but moving towards urql. Not sure how you've implemented the plugin but I suppose you can derive everything by just looking at the network requests, right? Or how does the Client Library matter? :)

For the subscriptions I'm currently using websockets.

**Comment by warrenday** [comment]
@anthonydelage I thought you'd like to know mocking is now available through a desktop version of the app. If you're on mac you can use this to proxy/intercept traffic from any site where introspection is possible. 

https://graphproxy.com

It's still in early beta but let me know what you think!

**Comment by robertherber** [comment]
@warrenday Hmm, I think I like this better as a browser extension on Desktop tbh.. :) Although an interesting prospect would be to have it on iPad/iPhone to look at requests inside apps since DevTools aren't available.

Just tried out the desktop app - and I still don't see subscriptions there - not sure if it's supposed to work there?

**Comment by anthonydelage** [comment]
Thanks for the update!

I'm having issues mocking some (but not all) GQL requests using the trial version. Is there a way to add auth to the introspector UI so I can mock internal APIs?

<img width="394" alt="Screen Shot 2022-03-31 at 13 52 07" src="https://user-images.githubusercontent.com/1356592/161119002-d9a77bdf-ad90-4042-b5a1-3fa5b2cb936b.png">

**Comment by warrenday** [comment]
You could add a query string `?token=1234` to the url if auth to your server is possible that way. There's currently no way of handling auth with headers (something I hadn't considered actually). Is there a particular auth method you need?

**Comment by anthonydelage** [comment]
We use a session-based cookie for auth. Would there be a way to pass that through the Chrome extension?

**Comment by warrenday** [comment]
I don't think it would be possible to route through the extension. But if headers are made available when running the introspection query tokens and cookies could be specified there. So i'll look at adding this.

**Comment by anthonydelage** [comment]
That'd be super helpful, thanks 👍

**Comment by OmarBurney** [comment]
Has there been any movement on support for subscriptions?

**Comment by brendanmorrell** [comment]
I would also very much like to see support for subscriptions. great library by the way.

**Comment by warrenday** [comment]
It is 100% in the roadmap. But I don't yet have a deadline.

**Comment by warrenday** [comment]
Closing as beta feature for subscriptions now added in 2.18.0. Let me know what you think and please raise any issues here on GitHub.

During beta the feature is disabled by default. Enable by selecting the subscription filter in the footer.

<img width="848" alt="Screenshot 2023-11-15 at 09 50 36" src="https://github.com/warrenday/graphql-network-inspector/assets/2871038/7a019a4d-e8db-4e4f-9378-003d3c3e1aed">

**Comment by brendanmorrell** [comment]
👏 👏 👏

**Comment by dontsave** [comment]
love this feature but also having the issue of seeing 0 bytes over the wire, with events coming through but empty in the extension

**Comment by warrenday** [comment]
Could you share some details of what you see in the standard network tab Vs the GraphQL tab?

**Comment by brendanmorrell** [comment]
Basically, I have maybe 4 subscriptions running, and the WS section of the actual network inspector shows many messages going back and forth. I am highlighting one in the screenshot so you can see they aren't just keep alive messages, but instead that there is actual data being sent from the client and then data being returned. Despite this, gql inspector is showing zero kb transferred/no messages. Can send any more details you need. just let me know specifically what you'd like to see.

<img width="1104" alt="Screenshot 2024-01-26 at 9 58 49 AM" src="https://github.com/warrenday/graphql-network-inspector/assets/14864397/55d7758c-e6fc-4825-b1fa-628e3161cc4a">

**Comment by brendanmorrell** [comment]
I also notice that it is picking up non-graphql subscriptions (see this image where it is grabbing a pub sub messaging subscription we use as well as webpack hot reloads (I am running our app locally in this screenshot)
<img width="697" alt="Screenshot 2024-01-26 at 10 06 27 AM" src="https://github.com/warrenday/graphql-network-inspector/assets/14864397/d04f81df-869d-4ed5-ab12-2c63be04e2bf">

**Comment by warrenday** [comment]
Thanks @brendanmorrell this is helpful. I'll update soon.

**Comment by warrenday** [comment]
@brendanmorrell I've looked at the main issue of requests not showing, and I've found the problem. Will release a fix shortly. It was purely that we were making strict assumptions on what shape the data should be in, which I've now made more flexible.

However, in the case of showing messages that are not GraphQL, this is more difficult to resolve.

For messages sent, it's not a problem, we can check the websocket payload and validate if it contains a graphql query. But for messages received, it's typically just JSON.

Even in the case of messages received over the graphql socket `wss://api.realize.me/v1/graphql` there are still lots of ping/pong messages, amongst other messages. 

It's not possible to know which received messages are desired to be shown or not. Potentially we could add a filter input to give control over to the user.

**Comment by warrenday** [comment]
<img width="986" alt="Screenshot 2024-02-04 at 16 19 25" src="https://github.com/warrenday/graphql-network-inspector/assets/2871038/b6d9662f-c891-41da-a944-19c8c95679c8">

It does seem sensible to assume received messages will contain a "data" key, which is very common in most graphql servers. Here is the subscription view with the new updates

**Comment by brendanmorrell** [comment]
Working great! Thanks @warrenday !

**Comment by jramiresbrito** [comment]
Hey guys, thanks for the great work on this extension and supporting the subscriptions.
Unfortunately, I'm not able to see anything in subscriptions
![image](https://github.com/warrenday/graphql-network-inspector/assets/47673606/94a674b5-dd65-4102-8483-cf47d7b7dea6)

Here's what I see in the network tab:
![image](https://github.com/warrenday/graphql-network-inspector/assets/47673606/78b517da-9b88-44bf-9649-b07a36299aac)

Any thoughts?

**Comment by warrenday** [comment]
Hey @anthonydelage that is unusual. Could you setup a basic example, repo or live service I can clone or visit. 

I'll be able to debug and deploy a patch.

**Comment by anthonydelage** [comment]
I think you meant to tag [jramiresbrito](https://github.com/jramiresbrito)?

**Comment by warrenday** [comment]
Oops sorry! Thank you.

**Comment by jramiresbrito** [comment]
@warrenday we managed to discover the problem. In your pr you was expecting the endpoint to contain **graphql**, we as rails users, were naming it as cable (because of action-cable). We simply added the graphql prefix it and worked! 

kudos to @tatosjb

![image](https://github.com/warrenday/graphql-network-inspector/assets/47673606/7006472d-e276-4b5f-8ed0-b39d54508fb6)
