### ISSUE TITLE
Allow whitelisting sites in chrome extension

### ISSUE THREAD

**Issue by repomaa** [warrenday/graphql-network-inspector#47]
The chrome extension permission for access to data of all websites sounds a bit scary so why not enable the chrome extension feature for setting up specific sites the extension can be active on or on click. It looks like react dev tools does this.

**Comment by warrenday** [comment]
We actually don't ask for any permissions so I have no idea why this message is now appearing. I'll need to talk to chrome support and update.

<img width="434" alt="Screenshot 2021-11-11 at 11 16 54" src="https://user-images.githubusercontent.com/2871038/141289095-c3cec6e9-61d1-4833-a9b1-48fccfc82580.png">

**Comment by warrenday** [comment]
Support got back and said although we do not request any permissions, the "access to data of all websites" message appears as the app does have access to network requests.

Looking at react devtools the same message also now appears "read and change all your data on all websites". I think unfortunately this is always going to be the case with these kinds of developer tools.

Hopefully given the fact this extension is open source you can have a better oversite of what you are installing.

<img width="545" alt="Screenshot 2021-11-30 at 20 21 45" src="https://user-images.githubusercontent.com/2871038/144122058-46336a49-b3cc-4c44-87ce-bffcffc56668.png">
"

**Comment by vitaliydolbilov** [comment]
Hi @warrenday, I'm following up this as our company requires us to whitelist certain extensions only to certain sites. The example of React dev tools does have the option to set site access to specific sites via a dropdown. This extension does not have that setting - 

<img width="676" alt="Screenshot 2023-04-18 at 12 44 56 PM" src="https://user-images.githubusercontent.com/103660206/232873847-722acbe6-afb9-4a04-8582-4682580830b6.png">

<img width="680" alt="Screenshot 2023-04-18 at 12 45 19 PM" src="https://user-images.githubusercontent.com/103660206/232873859-fbdf0d00-0555-4ce9-8eb4-165e68dd251d.png">

**Comment by warrenday** [comment]
Thanks for following up. Seems like this would be a common need for larger companies.

I'll take a look at adding something to the manifest to allow this.
