### ISSUE TITLE
UxUi improvements inside the `Response` explorer

### ISSUE THREAD

**Issue by tomma5o** [warrenday/graphql-network-inspector#52]
Hey @warrenday !
I'm here again 😄 

I would like to discuss to discuss about another improvement that could probably make sense(?)

When we have a bunch of requests grouped is hard to find the wanted one.

How about having the response key outside at the level or as a replacement of "1 item"

![image](https://user-images.githubusercontent.com/8134038/144095491-e4a45bae-5edc-4ce4-84bf-c94dc5304f96.png)

**Comment by warrenday** [comment]
Hello again :D @tomma5o 

The "Response" view uses `react-json-view` which has a collapsed prop. We could set this to level 3 in the case of batched queries which would look like:

<img width="735" alt="Screenshot 2021-11-30 at 20 07 52" src="https://user-images.githubusercontent.com/2871038/144120167-9a80e736-7dab-4676-9b85-cb4c3895d769.png">
<img width="505" alt="Screenshot 2021-11-30 at 20 09 15" src="https://user-images.githubusercontent.com/2871038/144120358-4fa5f804-0414-4c7e-b18b-a16ecc745b1a.png">

I think this could solve the pain point whilst keeping the meta of "1 item" which is more to show how many keys are in an object/array.

What do you think?

**Comment by tomma5o** [comment]
Yep absolutely agree on this!
I was thinking of a more difficult thing actually, the collapse at level 3 is perfect 👍

**Comment by warrenday** [comment]
Released version 2.7 which now collapses grouped responses at level 3. Should be on the store in the next couple of days.
