### ISSUE TITLE
Add "Copy Input" button for convenience

### ISSUE THREAD

**Issue by ZipBrandon** [warrenday/graphql-network-inspector#53]
**Is your feature request related to a problem? Please describe.**
I have to copy current requests from my app in GraphQL Network Inspector into GraphiQL for debugging or iteration.  It would be nice to have this convenience to copy that input.

**Describe the solution you'd like**
Add a button next to COPY for COPY INPUT.  Possibly change COPY to COPY REQUEST for disambiguation. 

**Describe alternatives you've considered**
Scrolling to the bottom of the Request, selecting all, and CMD-C.

**Additional context**
![image](https://user-images.githubusercontent.com/68867795/146404039-e25018df-ad83-44b6-8554-69f759457e5b.png)

**Comment by warrenday** [comment]
Hi @ZipBrandon are you referring to needing to copy the graphql variables? As the copy button should work with the request body.

**Comment by ZipBrandon** [comment]
Yes, @warrenday that's exactly what it should be. Copy Variables.  The copy button does indeed work with the body and is terrific!  Previous to this extension I was having to hand convert from the Network tab.

**Comment by warrenday** [comment]
Ok, i'll add the button. Hopefully it will make your job a little easier 👍

**Comment by warrenday** [comment]
Released version 2.7 which now contains copy vars button
