### ISSUE TITLE
Scrollbar for faster scrolling

### ISSUE THREAD

**Issue by cloneconf** [warrenday/graphql-network-inspector#54]
**Describe the solution you'd like**
Very simple... adding scroll bar :)

**Additional context**
This happens when the request content is very long.
I am using this extension on Brave Browser on xubuntu distro.

For example -that you can test-:

https://user-images.githubusercontent.com/88058138/147419407-83eca55a-93ad-4bdd-8b81-526c9bc09abe.mp4

**Comment by warrenday** [comment]
Hi @cloneconf I feel the pain on this one! Thanks for attaching the video. We'll take a look at adding a scrollbar which fits in nicely with the existing UI. I'll update once a version is released.

**Comment by warrenday** [comment]
Version 2.7.1 was just submitted. Should be available in the next few days.

<img width="768" alt="Screenshot 2022-01-06 at 16 45 15" src="https://user-images.githubusercontent.com/2871038/148418716-98c2e6ec-cdaa-4507-98d1-b97a0f31c9d0.png">

**Comment by cloneconf** [comment]
Cool @warrenday !
Thanks you very much :)
However is it also enabled for horizontal or not?
Anyway good work :heart:
