### ISSUE TITLE
Create firefox extension

### ISSUE THREAD

**Issue by lkuoch** [warrenday/graphql-network-inspector#59]
**Describe the solution you'd like**
Thank you for your extension! I'm a big fan of using it on Chrome and was hoping you would consider a release on firefox as well 🙏

**Describe alternatives you've considered**
There are no other firefox addons with this level of polish and productivity.

**Comment by warrenday** [comment]
Hi @lkuoch if you're on mac I have recently created a desktop version of the app which works with Firefox. You can give it a try for free https://graphproxy.com

Here you can see the app inspecting traffic on Firefox from https://medium.com
<img width="1440" alt="Screenshot 2022-03-30 at 13 00 09" src="https://user-images.githubusercontent.com/2871038/160829698-cce895d3-7694-47bf-add3-65f40125176a.png">

One of the major benefits is you can also mock traffic for any server which has introspection turned on. Try it out with this pokemon api https://graphql-pokeapi.graphcdn.app
<img width="1426" alt="Screenshot 2022-03-30 at 13 04 10" src="https://user-images.githubusercontent.com/2871038/160830437-b81119ef-44e9-4543-b1d9-ba4eb91d550b.png">

This is in early beta but let me know what you think!

**Comment by lkuoch** [comment]
> Hi @lkuoch if you're on mac I have recently created a desktop version of the app which works with Firefox. You can give it a try for free https://graphproxy.com
> 
> Here you can see the app inspecting traffic on Firefox from https://medium.com
> 
> <img alt="Screenshot 2022-03-30 at 13 00 09" width="1440" src="https://user-images.githubusercontent.com/2871038/160829698-cce895d3-7694-47bf-add3-65f40125176a.png">
> 
> One of the major benefits is you can also mock traffic for any server which has introspection turned on. Try it out with this pokemon api https://graphql-pokeapi.graphcdn.app
> 
> <img alt="Screenshot 2022-03-30 at 13 04 10" width="1426" src="https://user-images.githubusercontent.com/2871038/160830437-b81119ef-44e9-4543-b1d9-ba4eb91d550b.png">
> 
> This is in early beta but let me know what you think!

Would you mind if I published this as a firefox addon?

**Comment by warrenday** [comment]
@lkuoch you're welcome to raise a PR for the necessary changes. I'll then start publishing to Firefox as part of the deploy pipeline on this repo.

**Comment by falcucci** [comment]
@warrenday nice work!

IMO it should be listed in the readme for the millions of firefox users.

should I send a PR?

**Comment by warrenday** [comment]
Hey @falcucci 

The desktop version mentioned above didn't really catch on, so development stopped.

We can however build for Firefox as an extension since the browser api is almost identical. I think we just need to output a separate build here.

**Comment by forabi-cosuno** [comment]
@warrenday This is actually all it took for me to make this work in FF:


`public/devtools.js`

```js
chrome.devtools.panels.create(
  "GraphQL Network",
  "/icon.png",
  "/index.html",
  null
)
```
So basically, icon is required, and an absolute path to `index.html` must be provided instead of a relative one.

<img width="844" alt="Screenshot 2023-03-14 at 2 50 04 PM" src="https://user-images.githubusercontent.com/97028407/225022988-150da2c1-2062-4142-956e-1e1bc365ac1c.png">

Other than that, I think you could upload the exact same ZIP you get from `yarn bundle` to Mozilla Add-ons.

**Comment by tonycassara** [comment]
Any chance of an FF deploy soon? I just switched over at work and would love to get this into my workflow 🙌🏼

**Comment by Nezteb** [comment]
> Other than that, I think you could upload the exact same ZIP you get from `yarn bundle` to Mozilla Add-ons.

@warrenday What were your steps?

I tried creating that `public/devtools.js` file, building the bundle, renaming the `build.zip` file to `build.xpi`, and importing it into Firefox, but I only get:
<img width="414" alt="Screenshot 2023-04-19 at 3 50 52 PM" src="https://user-images.githubusercontent.com/3588798/233217012-955917e6-6d60-4f11-a5d7-18e5bf662d2a.png">

**Comment by forabi-cosuno** [comment]
@Nezteb that's probably because it's not signed. I only used it in development mode which allows unsigned addons

**Comment by forabi-cosuno** [comment]
Alternatively, you could just import the whole folder in dev mode instead of the zip

**Comment by Nezteb** [comment]
> I only used it in development mode which allows unsigned addons

Huh, I am using LibreWolf so I wouldn't be surprised if that is causing issues. I did try to allow unsigned extensions in `about:config` to no avail:
<img width="722" alt="Screenshot 2023-04-29 at 9 30 17 PM" src="https://user-images.githubusercontent.com/3588798/235335574-c04546cc-0e34-435e-973e-06c47b26abdb.png">

**Comment by Nezteb** [comment]
Ah, okay I figured out the problem.

> Other than that, I think you could upload the exact same ZIP you get from yarn bundle to Mozilla Add-ons.

@forabi-cosuno This isn't the case apparently. Firefox expects a slightly different file structure and (when trying to install from a local build) a slightly different `manifest.json`.

An example Yarn script that would fix the directory issue: (zipping the files at the top level instead of the entire directory)
```json
"bundle": "yarn build && bestzip build.zip build/*",
"firefox": "yarn build && cd build && bestzip ../build.zip *",
```

And since an extension ID isn't generated for local ZIP/XPI extensions, you need to add one to the `manifest.json`, but only when wanting to install a local build: (the actual ID doesn't matter)
```json
"browser_specific_settings": {
  "gecko": {
    "id": "addon@example.com"
  }
},
```

After those two changes, I'm able to install the extension locally and don't need to use the "temporary extension" method. 😄

**Comment by forabi-cosuno** [comment]
Here's a signed FF version: 
[9f262261e149424993ae-2.14.1.zip](https://github.com/warrenday/graphql-network-inspector/files/11404392/9f262261e149424993ae-2.14.1.zip) (Rename to .xpi before using)

**Comment by warrenday** [comment]
Looks like it's not hard work at all to get this released officially. I'll update the codebase and start releasing a long with chrome.

**Comment by tonycassara** [comment]
Any chance FF has approved the extension yet? Excited to use this!

**Comment by kud** [comment]
Currently using the @forabi-cosuno 's version but yeah can't wait to have this in the FF store.

**Comment by warrenday** [comment]
Firefox bundling has now been added. Thanks to all on this thread for pointers to get this working. It's been a great help.

I have tested a local version and submitted to the Firefox Add-Ons developer hub. I'll update when we have a live listing. ❤️

**Comment by brianvanburken** [comment]
I see that it is ready to install! :) https://addons.mozilla.org/en-US/firefox/addon/graphql-network-inspector/ Thank you @warrenday!

**Comment by warrenday** [comment]
I'll close this issue now as we have an official release!
