### ISSUE TITLE
GraphQL tab not appearing on Chrome

### ISSUE THREAD

**Issue by GeeDat** [warrenday/graphql-network-inspector#62]
**Describe the bug**
The GraphQL tab no longer appears in Chrome DevTools. Closing and opening the Dev Tools (F12) multiple times will usually make it appear but today nothing is working. It has worked perfectly until 2-3 weeks ago

**To Reproduce**
1) Go to a page using GraphQL in Chrome. 2) Hit F12. 
3) Dev Tools appear
4) GraphQL tab does not appear

**Expected behavior**
Grpah QL tab will appear in DevTools on Chrome

**Desktop (please complete the following information):**

- OS: Mac OS Monterey 12.3
- Chrome Version 99.0.4844.83 (Official Build) (x86_64)

**Comment by warrenday** [comment]
Are other devtools extensions also not loading?

I have had this issue before when my chrome account was synced between two machines. One had the extensions and one didn't causing it to disappear.

Hard to point to the actual reason though. I'll try to recreate on my end but haven't had the same issue so far.

**Comment by GeeDat** [comment]
HI, It is only the GraphQL devtool. My other 2 colleagues who use the tool have been reporting the same. This morning. I closed Chrome down completely and re-opened and it came back after a few F12s. I'll see if it gets worse over time again.

**Comment by warrenday** [comment]
Ok thanks for raising, slightly concerning. Yeah please update if the issue persists.

**Comment by warrenday** [comment]
Hey @GeeDat I thought you may also be interested to know there is also a desktop version of the app. If you're on mac this will allow you to inspect traffic from any app/browser plus do things like mock live requests with mock data.

You can download the app from here https://graphproxy.com

Give the mocking a try on this pokemon api https://graphql-pokeapi.graphcdn.app
<img width="1426" alt="Screenshot 2022-03-30 at 13 04 10" src="https://user-images.githubusercontent.com/2871038/160831177-85149031-9bcd-41f3-934e-398669c0e1af.png">

Or checkout the general network inspector at https://medium.com

This is in early beta so let me know what you think!

**Comment by GeeDat** [comment]
Hi, Thanks Warren,
I already use Insomnia for most of my GraphQL dev testing/mocking. The
great thing about the browser version is I can open it in a rtab next to a
page and see/test the queries with no need to set up authorization stuff,
so it is super quick for sanity what is being reported on other
environments.

George

**Comment by Xapphire13** [comment]
@warrenday, this issue started happening for me and a number of coworkers. Maybe a Chrome update caused it to stop working?

My coworkers use Chrome, but I use Microsoft Edge and I was working for me until this week when Edge updated to `115.0.1901.200`

**Comment by Odonno** [comment]
I can confirm this. I had to close/reopen DevTools on Edge to see the tab again. This is the first time this has ever happened.

**Comment by warrenday** [comment]
No updates on our side, so it will be related to a new browser release. I'll take a look and see what could be causing.

Is this only affecting graphql inspector, or other custom dev extensions too?

**Comment by Xapphire13** [comment]
Seems be to limited to GraphQL Network Explorer, React and Apollo extensions for example are behaving correctly.

**Comment by warrenday** [comment]
@Xapphire13 Could you confirm your operating system details?

I've just tested on latest Edge and Chrome with Mac (M1 Chip) - both are loading the extension. Potentially could be a windows issue, or a non apple silicon mac.

**Comment by warrenday** [comment]
Closing as we have a new thread for this
https://github.com/warrenday/graphql-network-inspector/issues/111
