### ISSUE TITLE
Response/Request headers `Copy` Button

### ISSUE THREAD

**Issue by tomma5o** [warrenday/graphql-network-inspector#69]
Hey @warrenday, happy to be here again 😄 

---

**Is your feature request related to a problem? Please describe.**
When inspecting Queries/Mutations and want to copy headers of that call for using it in the GQL playground, it copies in the clipboard an array of headers that is the wrong format for the playground because it requires an object

**Describe the solution you'd like**
The copy button copies an object not an array of values

**Additional context**
![Screenshot 2022-05-28 at 18 41 36](https://user-images.githubusercontent.com/8134038/170834703-dfaac5f0-5128-4634-8049-766bf5d3aa18.png)

Happy to open a PR for this if u think it could be a good idea,
dunno what was the reason for that choice, maybe postman &co. prefer that format!

WDYT?

**Comment by warrenday** [comment]
Hello again!

Happy to change the format of this although I wouldn't want to change how it works for users who are happy with the current format.

We could potentially make this a configuration option so users can choose which format headers are copied as. 

Potentially the button could have a dropdown option to copy as array or copy as object.

Something along those lines?

**Comment by tomma5o** [comment]
Yep, I agree.
Honestly, I prefer the dropdown in the button.

I think it's the fastest way because we don't have a configuration file AFAIK in the chrome-extension.
