### ISSUE TITLE
Fragement name instead of mutation name displayed

### ISSUE THREAD

**Issue by vkhansen** [warrenday/graphql-network-inspector#7]
When going through this site: https://demo.saleor.io/ there is a slight mistake in that the name of fragment is displayed instead of the name of the mutation

Bug Behavior:
Mutation name displayed as "Price"

Price is a fragment used by the mutation not he main mutation.

Expected Behavior:
Mutation name displayed as "UpdateCheckoutShippingMethod"

![Screen Shot 2564-04-02 at 14 39 54](https://user-images.githubusercontent.com/42178039/113394126-e717cd00-93c1-11eb-8b36-0d7a7bf3234c.png)

![Screen Shot 2564-04-02 at 14 39 42](https://user-images.githubusercontent.com/42178039/113394113-e3844600-93c1-11eb-869a-c4d5b64a5c0d.png)

**Comment by warrenday** [comment]
@vkhansen thanks for raising this. I can recreate the issue and have a PR ready to go. I'll release to dev store this week.
https://github.com/warrenday/graphql-network-inspector/pull/8
