### ISSUE TITLE
Add uninstall instructions to readme

### ISSUE THREAD

**Issue by pistachiomatt** [warrenday/graphql-network-inspector#74]
If one decides the product isn't for them, it's unclear how to uninstall it.

Add to the readme:
1. Instructions for removing the SSL certificate
2. Instructions for removing the proxy (which sometimes stays checked in Network Preferences.)

**Comment by warrenday** [comment]
I've added some initial uninstall instructions to the site. I'll update the readme of this repo also.

https://graphproxy.com/docs/#uninstall
