### ISSUE TITLE
Can't Read or Change Site's data

### ISSUE THREAD

**Issue by lihebi** [warrenday/graphql-network-inspector#83]
**Describe the bug**
The extension icon is grayed out and says "Can't read or Change site's data". I've tried quitting and re-opening chrome, not working. I've also tried Chrome Canary and Firefox, all with the same issue.

**To Reproduce**

1. install GraphQL Inspector chrome extension
2. Click on extension icon

**Expected behavior**
Not grayed out, and show a tab in the developer console.

**Screenshots**
<img width="327" alt="Screenshot 2023-02-27 at 11 08 34 AM" src="https://user-images.githubusercontent.com/4576201/221464118-9db0f628-c914-44cd-8b64-ffcae72602e3.png">

**Desktop (please complete the following information):**

- OS: macOS 13.1
- Chrome Version: Version 110.0.5481.100 (Official Build) (arm64)

**Comment by Odonno** [comment]
This is not a bug. You can only use this extension by opening the DevTools and click on the "GraphQL Network" tab:

![image](https://user-images.githubusercontent.com/6053067/221593538-0b1e27f2-8935-4e4f-8968-3c31a999836a.png)

I think this is not the first time people are saying this. I believe we should update the readme to explain how this extension works.

**Comment by lihebi** [comment]
Ah, I see; there is a "GraphQL Network" tab.

<img width="559" alt="Screenshot 2023-02-28 at 4 57 32 PM" src="https://user-images.githubusercontent.com/4576201/221803419-19cf1d14-cddd-4345-b548-29e3974bd8ef.png">

**Comment by warrenday** [comment]
I'll update the readme. Thanks for raising!
