### ISSUE TITLE
Enable Vercel Deployment

### ISSUE THREAD

**Issue by Odonno** [warrenday/graphql-network-inspector#87]
**Is your feature request related to a problem? Please describe.**

Instead of asking for screenshots on each PR, you can enable Vercel Deployment on your repository so that you can interact directly with a preview environment.

Here is how it works: https://vercel.com/features/previews

You can also use the new feature where you can write comments on the preview environment, like if you want to discuss about the design of a component for example.

@warrenday You are 3 clicks away from enabling Vercel on your repository and it is totally free for this kind of project.

**Comment by warrenday** [comment]
Great idea! Thanks for recommending.

**Comment by warrenday** [comment]
Close as no plans to move to vercel.
