### ISSUE TITLE
Easier to view Vars

### ISSUE THREAD

**Issue by joeshub** [warrenday/graphql-network-inspector#92]
**Is your feature request related to a problem? Please describe.**
If the request is really large, there is often the need to scroll down quite a bit until you can view the vars section. It currently happens when your query has lots of fragments that contain fragments etc.

**Describe the solution you'd like**
I can think of a few of solutions, sorted in order of difficulty and or functionality.
- Make a new separate tab just for Vars
- Move the vars to the top, above the query
- Make it so clicking on the Copy Vars button, also jumps to the section where the vars are shown.

Also open to any other suggestions or ideas.

**Comment by Odonno** [comment]
Fourth solution: #88

**Comment by warrenday** [comment]
Are you working on this one @Odonno . I don't mind doing it if you haven't already started.

**Comment by Odonno** [comment]
@warrenday Nope. You can take it. I am curious how you are going to do it. Are you planning to use headlessui or any kind of library for this?

**Comment by joeshub** [comment]
thank you @warrenday and @Odonno
