### ISSUE TITLE
no requests are written

### ISSUE THREAD

**Issue by luankkobs** [warrenday/graphql-network-inspector#97]
**Describe the bug**
The extension in question appears as disabled and no requests are written when opening GraphQL (F12)

**To Reproduce**
Just install the plugin and make a request

**Screenshots**
![image](https://user-images.githubusercontent.com/52356761/234622139-216c59e2-7bf8-474d-9f0d-d5a98bf887f2.png)
![no request](https://user-images.githubusercontent.com/52356761/234622509-c5bf7f9f-2432-42a8-bbd8-8023b7ffec4b.gif)

- OS: [Ubuntu 20.04]
- Chrome Version [12.0.5615.49 (Official Build) (64-bit)]

**Comment by Odonno** [comment]
Hi @luankkobs 

You need to be on a website that generate GraphQL query or mutation. You can try this website for example: https://medium.com/

To be honest, this extension is really useful when using GraphQL on your own projects. Otherwise, not so much.

**Comment by warrenday** [comment]
Just to echo @Odonno we only parse standard GraphQL queries. So if you're on a website that is using non-standard GraphQL like Twitter, or a website that doesn't use GraphQL at all like Google, you won't see any data.

**Comment by warrenday** [comment]
Hi @apatidar1986 please provide a link that shows the web request and I can help debug.

**Comment by warrenday** [comment]
Closing as using a non supported website.
